import { describe, expect, it } from "vitest";
import type { ThemeDefinition } from "./tokens";
import { themeToCssVariables } from "./style";

const testTheme: ThemeDefinition = {
  id: "test-light",
  label: "Test Light",
  family: "Test",
  scheme: "light",
  tokens: {
    app: {
      bg: "#ffffff",
      text: "#111111",
      panel: "#f8f8f8",
      panelMuted: "#eeeeee",
      border: "#dddddd",
      textMuted: "#666666",
      tabText: "#555555",
      hover: "#e8e8e8",
      focus: "#3366ff",
      errorBg: "#fff0f0",
      errorBorder: "#ffaaaa",
      errorText: "#771111",
      dialogShadow: "0 18px 54px rgb(0 0 0 / 18%)",
      backdrop: "rgb(0 0 0 / 24%)",
    },
    editor: {
      text: "#202020",
      textMuted: "#707070",
      bg: "#ffffff",
      surface: "#f7f7f7",
      surfaceElevated: "#fafafa",
      border: "#dddddd",
      link: "#0055aa",
      linkHover: "#003f80",
      selection: "rgb(0 85 170 / 24%)",
      caret: "currentColor",
      focusRing: "#3366ff",
      scrollbarThumb: "rgb(0 0 0 / 28%)",
      scrollbarThumbHover: "rgb(0 0 0 / 42%)",
    },
    markdown: {
      codeFg: "#202020",
      codeBg: "rgb(0 0 0 / 8%)",
      codeFenceBg: "rgb(0 0 0 / 6%)",
      codeHeaderBg: "rgb(0 0 0 / 8%)",
      blockquoteBorder: "rgb(0 0 0 / 28%)",
      blockquoteFg: "#555555",
      divider: "rgb(0 0 0 / 24%)",
      tableBorder: "rgb(0 0 0 / 24%)",
      checkboxAccent: "#0055aa",
    },
    syntax: {
      keyword: "#7a3db8",
      string: "#237a57",
      number: "#9a5d28",
      comment: "#777777",
      variable: "#1f4f99",
      type: "#7a4f00",
      function: "#005f87",
      operator: "#555555",
      punctuation: "#555555",
    },
  },
};

describe("themeToCssVariables", () => {
  it("maps app, editor, markdown, and syntax tokens to CSS variables", () => {
    expect(themeToCssVariables(testTheme)).toEqual({
      colorScheme: "light",
      "--app-bg": "#ffffff",
      "--app-text": "#111111",
      "--app-panel": "#f8f8f8",
      "--app-panel-muted": "#eeeeee",
      "--app-border": "#dddddd",
      "--app-text-muted": "#666666",
      "--app-tab-text": "#555555",
      "--app-hover": "#e8e8e8",
      "--app-focus": "#3366ff",
      "--app-error-bg": "#fff0f0",
      "--app-error-border": "#ffaaaa",
      "--app-error-text": "#771111",
      "--app-dialog-shadow": "0 18px 54px rgb(0 0 0 / 18%)",
      "--app-backdrop": "rgb(0 0 0 / 24%)",
      "--ge-color-text": "#202020",
      "--ge-color-text-muted": "#707070",
      "--ge-color-bg": "#ffffff",
      "--ge-color-surface": "#f7f7f7",
      "--ge-color-surface-elevated": "#fafafa",
      "--ge-color-border": "#dddddd",
      "--ge-color-link": "#0055aa",
      "--ge-color-link-hover": "#003f80",
      "--ge-color-selection": "rgb(0 85 170 / 24%)",
      "--ge-color-caret": "currentColor",
      "--ge-color-focus-ring": "#3366ff",
      "--ge-color-scrollbar-thumb": "rgb(0 0 0 / 28%)",
      "--ge-color-scrollbar-thumb-hover": "rgb(0 0 0 / 42%)",
      "--ge-color-code-fg": "#202020",
      "--ge-color-code-bg": "rgb(0 0 0 / 8%)",
      "--ge-color-code-fence-bg": "rgb(0 0 0 / 6%)",
      "--ge-color-code-header-bg": "rgb(0 0 0 / 8%)",
      "--ge-color-blockquote-border": "rgb(0 0 0 / 28%)",
      "--ge-color-blockquote-fg": "#555555",
      "--ge-color-divider": "rgb(0 0 0 / 24%)",
      "--ge-color-table-border": "rgb(0 0 0 / 24%)",
      "--ge-color-checkbox-accent": "#0055aa",
      "--ge-color-token-keyword": "#7a3db8",
      "--ge-color-token-string": "#237a57",
      "--ge-color-token-number": "#9a5d28",
      "--ge-color-token-comment": "#777777",
      "--ge-color-token-variable": "#1f4f99",
      "--ge-color-token-type": "#7a4f00",
      "--ge-color-token-function": "#005f87",
      "--ge-color-token-operator": "#555555",
      "--ge-color-token-punctuation": "#555555",
      "--ge-shadow-editor": "none",
    });
  });
});
