import type { ThemeCssVariables, ThemeDefinition } from "./tokens";

export function themeToCssVariables(theme: ThemeDefinition): ThemeCssVariables {
  const { app, editor, markdown, syntax } = theme.tokens;

  return {
    colorScheme: theme.scheme,
    "--app-bg": app.bg,
    "--app-text": app.text,
    "--app-panel": app.panel,
    "--app-panel-muted": app.panelMuted,
    "--app-border": app.border,
    "--app-text-muted": app.textMuted,
    "--app-tab-text": app.tabText,
    "--app-hover": app.hover,
    "--app-focus": app.focus,
    "--app-error-bg": app.errorBg,
    "--app-error-border": app.errorBorder,
    "--app-error-text": app.errorText,
    "--app-dialog-shadow": app.dialogShadow,
    "--app-backdrop": app.backdrop,
    "--ge-color-text": editor.text,
    "--ge-color-text-muted": editor.textMuted,
    "--ge-color-bg": editor.bg,
    "--ge-color-surface": editor.surface,
    "--ge-color-surface-elevated": editor.surfaceElevated,
    "--ge-color-border": editor.border,
    "--ge-color-link": editor.link,
    "--ge-color-link-hover": editor.linkHover,
    "--ge-color-selection": editor.selection,
    "--ge-color-caret": editor.caret,
    "--ge-color-focus-ring": editor.focusRing,
    "--ge-color-scrollbar-thumb": editor.scrollbarThumb,
    "--ge-color-scrollbar-thumb-hover": editor.scrollbarThumbHover,
    "--ge-color-code-fg": markdown.codeFg,
    "--ge-color-code-bg": markdown.codeBg,
    "--ge-color-code-fence-bg": markdown.codeFenceBg,
    "--ge-color-code-header-bg": markdown.codeHeaderBg,
    "--ge-color-blockquote-border": markdown.blockquoteBorder,
    "--ge-color-blockquote-fg": markdown.blockquoteFg,
    "--ge-color-divider": markdown.divider,
    "--ge-color-table-border": markdown.tableBorder,
    "--ge-color-checkbox-accent": markdown.checkboxAccent,
    "--ge-color-token-keyword": syntax.keyword,
    "--ge-color-token-string": syntax.string,
    "--ge-color-token-number": syntax.number,
    "--ge-color-token-comment": syntax.comment,
    "--ge-color-token-variable": syntax.variable,
    "--ge-color-token-type": syntax.type,
    "--ge-color-token-function": syntax.function,
    "--ge-color-token-operator": syntax.operator,
    "--ge-color-token-punctuation": syntax.punctuation,
    "--ge-shadow-editor": "none",
  };
}
